// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeatsProject.Models;

#nullable disable

namespace SeatsProject.Migrations
{
    [DbContext(typeof(SeatsProjectContext))]
    [Migration("20230907092647_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeatsProject.Models.Prenotazioni", b =>
                {
                    b.Property<int>("IdPrenotazine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrenotazine"));

                    b.Property<string>("CodicePostazione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodicePrenotazione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Utente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPrenotazine");

                    b.ToTable("Prenotazioni");
                });

            modelBuilder.Entity("SeatsProject.Models.Sede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodiceArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdPadre")
                        .HasColumnType("int");

                    b.Property<string>("ImmagineSvg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Prenotabile")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Sedi");
                });
#pragma warning restore 612, 618
        }
    }
}
